apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://52.39.244.88:6443
    k8sVersion: v1.8.2
    path: default
kind: ksonnet.io/app
libraries:
  core:
    gitVersion:
      commitSha: b497fd581c823ba3911296ec58c072a48c57c474
      refSpec: v0.1.2
    name: core
    registry: kubeflow
  tf-job:
    gitVersion:
      commitSha: b497fd581c823ba3911296ec58c072a48c57c474
      refSpec: v0.1.2
    name: tf-job
    registry: kubeflow
  tf-serving:
    gitVersion:
      commitSha: b497fd581c823ba3911296ec58c072a48c57c474
      refSpec: v0.1.2
    name: tf-serving
    registry: kubeflow
name: ucp-kubeflow
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    gitVersion:
      commitSha: b497fd581c823ba3911296ec58c072a48c57c474
      refSpec: v0.1.2
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.1.2/kubeflow
version: 0.0.1
